### ISSUE TITLE
Is the secret in oauth_app really equivalent to a password?

### ISSUE THREAD

**Issue by jennybc** [hadley/httr#221]
This documentation doesn't seem right (or else I've done a Very Bad Thing):

https://github.com/hadley/httr/blob/75aca2bd9c7a87b2806cf5806dbc96fee07979f2/R/oauth-app.r#L12-L16

> secret	consumer secret. This is equivalent to a password and should not be stored in publicly visible code. As a convenient shortcut, if secret is missing, we'll look in the environment variable APPNAME_CONSUMER_SECRET. Use NULL to not store a secret: this is useful if you're relying on cached OAuth tokens.

And it seems to contradict this bit in the api-packages vignette:

> OAuth 2.0. Very common in modern web apps. It involves a round trip between the client and server to establish if the API client has the authority to access the data. See oauth2.0_token(). It's ok to publish api key and "secret" - these are not actually important for security of user data.

**Comment by karthik** [comment]
The documentation is just a bit outdated. You haven't done anything wrong or bad.

When you create an application, and obtain a key/secret, that combo allows anyone to access that service, but not individual accounts within that service. And most often (outside of R) these keys are shipped _inside_ binary programs (e..g ios apps), so no one else can take them and reuse them.  But users can still say, connect to my Dropbox/Amazon etc and they authorise your application to access their accounts. For R it's a bit unusual in that we cannot hide anything in the source. Nothing bad will come from exposing these keys. Worst case someone uses it for a different application because they are too lazy to get their own, and perhaps that might abuse the TOS by submitting too many requests, use service to spam etc, but those are often automatically shut down and the keys are invalidated. No one's individual account is touched. So no security issues as far as user data. Worst case is disruption because now you (or a user) has to generate new keys to continue using the app.
