### ISSUE TITLE
jwt_claimset in oauth_service_token hardcodes aud and does not take endpoint URL

### ISSUE THREAD

**Issue by makanig** [hadley/httr#273]
Here is the code that should work but breaks because of the hardcoding of aud:

```
endpoint <- oauth_endpoint(authorize= "https://www.googleapis.com/oauth2/v3/token", 
                          access = "https://www.googleapis.com/oauth2/v3/token", 
                           base_url = "https://www.googleapis.com")
# endpoint <- oauth_endpoints("google") # this is for accounts.google.com, I need GCP access

secrets <- jsonlite::fromJSON(keyFile)
scope <- "https://www.googleapis.com/auth/devstorage.read_write"


gtoken <- oauth_service_token(endpoint, secrets, scope)
```
Hardcoding by the function

```
jwt_claimset <- function(iss, scope,
                         aud = "https://accounts.google.com/o/oauth2/token",
                         exp = NULL, iat = NULL) {
```

**Comment by hadley** [comment]
Where should that parameter come from? Any thoughts @siddharthab, @craigcitro?

**Comment by siddharthab** [comment]
I suppose the reason why this was OK to be hardcoded was because the documentation said that this will always be this value (the value now in the documentation is different from what is hardcoded in httr):

From https://developers.google.com/identity/protocols/OAuth2ServiceAccount > Preparing to make an authorized API call > HTTP/REST
> aud	A descriptor of the intended target of the assertion. When making an access token request this value is always https://www.googleapis.com/oauth2/v4/token.

If something else uses this mechanism but a different AUD value, then I suppose we can make it configurable by the user.

**Comment by makanig** [comment]
I had filed the bug when working with Google Cloud Platform (GCP)..your code worked for Google acct APIs but did not handle the Google cloud APIs endpoint which is different.

If you can allow passed in parameters that makes it flexible. You can keep the same default for Google acct APIs.

**Comment by hadley** [comment]
I now take it from the service file, so this should be good.
