### ISSUE TITLE
Problem with POST request

### ISSUE THREAD

**Issue by sckott** [hadley/httr#65]
I'm getting this `curl` call to work just fine 

`curl --form "file=@myfile.txt" http://taxosaurus.org/submit`

Where myfile.txt is 

```
"Dichorisandra diederichsanae"
"Echeveria longiflora"
"Gottschea cuspidiloba"
"Virola loretensis"
"Pterobryella praenitens"
"Ochthocosmus floribundus"
"Geissois superba"
"Ginkgo biloba"
"Escallonia angustifolia"
"Pterigynandrum julaceum"
```

But I can't quite get this to work using `POST` or `postForm`. I think I'm missing something obvious, but I don't know what it might be.

**Comment by antoine-lizee** [comment]
@hadley 
> Curl then complains
```
* Issue another request to this URL: 'http://taxosaurus.org/retrieve/6a21cece1e782dfa7e6f149dd0793c91'
* Violate RFC 2616/10.3.3 and switch from POST to GET
```

This is actually a false positive. It would violate the RFC by default and issue a `GET` for the redirect (as expected by the server) but *it doesn't in this case* because the `customrequest` (`CURLOPT_CUSTOMREQUEST `) options takes precedence. This is an undesirable side effect of using `customrequest` instead of the method flags. `httr` doesn't follow redirects properly as a result. (see https://github.com/hadley/httr/issues/356)
