### ISSUE TITLE
HTTR Error installing

### ISSUE THREAD

**Issue by mercearisaa** [hadley/httr#750]
I tried to install HTTR package, when the dowload is complete and i tried to run a function with this package R says "Error package is not installed". I tried to reinstall R Studio with another previous version (because I had the newer one), and the R still going. I don't know what i can do. )): 
Ty <3
<img width="1126" alt="Captura de pantalla 2024-05-22 a las 11 29 42" src="https://github.com/r-lib/httr/assets/170514636/b3ac0256-b565-45f5-b783-652240d24a30">

**Comment by jennybc** [comment]
I see two possible, interacting problems you might want to run down.

One: I bet you need to re-accept the EULA for Xcode command line tools. Look at threads like this to resolve: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Two: Are you really committed to being on R 4.1? That is quite far behind what's current (4.4) and it's why, instead of getting easy-to-install binary package from CRAN, you've having to compile everything locally, in order to install it.
