### ISSUE TITLE
has_content

### ISSUE THREAD

**Issue by hadley** [hadley/httr#91]
Boolean if there's any content associated with request. `as = "auto"` should throw an error.

**Comment by jennybc** [comment]
Here's [current definition of `has_content()`](https://github.com/hadley/httr/blob/e8a85c0a137c543090b60c694ea4d332e4833d68/R/content.r#L100-L109):

```r
has_content <- function(x) {
  length(x) == 0
}
```

I'm trying to use it over in my PR re: `devtools` and ... any chance you meant this to involve `content(x)` instead of `x` and/or to test if length is *greater than zero*? I can't find any usage of `has_content()` any where on github, so I can't figure out if I'm just missing something ... but this seems really weird.

**Comment by hadley** [comment]
Hmmm seems like it should be `length(x$content) > 0` :/
